# Generated by Django 4.1.5 on 2023-01-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('numberOfHours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
                ('student', models.ManyToManyField(related_name='student',
                 through='school.Statement', to='school.student')),
                ('subject', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(
                related_name='teacher', through='school.Statement', to='school.teacher'),
        ),
        migrations.AddField(
            model_name='statement',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AddField(
            model_name='statement',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('subject', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
            ],
        ),
    ]
