# Generated by Django 4.1.4 on 2023-01-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='teacher',
        ),
        migrations.AddField(
            model_name='statement',
            name='student',
            field=models.ManyToManyField(blank=True, to='school.student'),
        ),
        migrations.AddField(
            model_name='statement',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='school.teacher'),
        ),
    ]
